force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <description>Contains attributes describing a bus.</description>
    <label>Bus</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Bus Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Air_Conditioned__c.field-meta.xml
<CustomField>
    <fullName>Air_Conditioned__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if the bus has air conditioning.</inlineHelpText>
    <label>Air Conditioned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Maximum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Capacity__c</fullName>
    <inlineHelpText>The maximum capacity.</inlineHelpText>
    <label>Maximum Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Model_Year__c.field-meta.xml
<CustomField>
    <fullName>Model_Year__c</fullName>
    <inlineHelpText>The model year of the bus.</inlineHelpText>
    <label>Model Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Reading__c</fullName>
    <inlineHelpText>The most recently recorded odometer reading.</inlineHelpText>
    <label>Odometer Reading</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Resale_Value__c.field-meta.xml
<CustomField>
    <fullName>Resale_Value__c</fullName>
    <inlineHelpText>The current resale value of the bus.</inlineHelpText>
    <label>Resale Value</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The bus status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Use</fullName>
            </value>
            <value>
                <fullName>Scheduled for Maintenance</fullName>
            </value>
            <value>
                <fullName>Undergoing Repairs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BusTrgHandler.cls
public with sharing class BusTrgHandler {

    public static boolean RunOnce = false;

    public static void onAfterInsert(List<Bus__c> insertedBuses) {
        List<Bus__c> busesToUpdate = ComputeResaleValues(insertedBuses);
        UPDATE busesToUpdate;
    }

    public static void onAfterUpdate(List<Bus__c> updatedBuses) {
        List<Bus__c> busesToUpdate = ComputeResaleValues(updatedBuses);
        UPDATE busesToUpdate;
    }

    private static List<Bus__c> ComputeResaleValues(List<Bus__c> buses) {
        List<Bus__c> busesToUpdate = new List<Bus__c>();        
        for (Bus__c bus : buses) {
            double resaleValue = 0;
            if (bus.Status__c == 'Ready For Use') {
                if (integer.valueOf(bus.Maximum_Capacity__c) == 24) {
                    resaleValue = 120000;                    
                }
                else if (integer.valueOf(bus.Maximum_Capacity__c) == 36) {
                    resaleValue = 160000;
                }                

                if (resaleValue > 0) {
                    if (integer.valueOf(bus.Model_Year__c) < 1973) {
                        // bus is historic, increase value by 34%.
                        resaleValue = resaleValue + (resaleValue * .34);
                    }

                    double milesReduction = bus.Odometer_Reading__c - 100000;
                    if (milesReduction > 0) {
                        // reduce value by 10 cents per mile over 100000.
                        resaleValue = resaleValue - (milesReduction * .1);
                    }

                    if (bus.Air_Conditioned__c) {
                        // bus with AC is worth 3% more.
                        resaleValue = resaleValue + (resaleValue * .03);
                    }
                }
            }
            Bus__c busToUpdate = new Bus__c();
            busToUpdate.Id = bus.Id;
            busToUpdate.Resale_Value__c = resaleValue;
            busesToUpdate.Add(busToUpdate);
    }
        return busesToUpdate;
    }
}