force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <description>Contains attributes describing a bus.</description>
    <label>Bus</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Bus Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Air_Conditioned__c.field-meta.xml
<CustomField>
    <fullName>Air_Conditioned__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if the bus has air conditioning.</inlineHelpText>
    <label>Air Conditioned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Bus_Picture__c.field-meta.xml
<CustomField>
    <fullName>Bus_Picture__c</fullName>
    <inlineHelpText>Picture of the bus.</inlineHelpText>
    <label>Bus Picture</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Last_Reported_Location__c.field-meta.xml
<CustomField>
    <fullName>Last_Reported_Location__c</fullName>
    <inlineHelpText>The last reported location of the bus.</inlineHelpText>
    <label>Last Reported Location</label>
    <scale>4</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Maximum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Capacity__c</fullName>
    <inlineHelpText>The maximum capacity.</inlineHelpText>
    <label>Maximum Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Model_Year__c.field-meta.xml
<CustomField>
    <fullName>Model_Year__c</fullName>
    <inlineHelpText>The model year of the bus.</inlineHelpText>
    <label>Model Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Number_Of_Wheels__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Wheels__c</fullName>
    <inlineHelpText>The number of wheels the bus has.</inlineHelpText>
    <label>Number of Wheels</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Reading__c</fullName>
    <inlineHelpText>The most recently recorded odometer reading.</inlineHelpText>
    <label>Odometer Reading</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Resale_Value__c.field-meta.xml
<CustomField>
    <fullName>Resale_Value__c</fullName>
    <inlineHelpText>The current resale value of the bus.</inlineHelpText>
    <label>Resale Value</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The bus status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Use</fullName>
            </value>
            <value>
                <fullName>Scheduled for Maintenance</fullName>
            </value>
            <value>
                <fullName>Undergoing Repairs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Bus.cls
public with sharing class Bus {

    @AuraEnabled
    public static List<Bus__c> getBuses() {
        try {
            return [
                SELECT Id
                    ,Name
                    ,Bus_Picture__c
                    ,Status__c
                FROM Bus__c
                ORDER BY Name
            ];
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static Bus__c getBus(string busId){
        try {
            if (busId == '') {
                return new Bus__c();
            }
            else {
                return [
                    SELECT Id
                        ,Name
                        ,Air_Conditioned__c
                        ,Bus_Picture__c
                        ,Last_Reported_Location__c
                        ,Maximum_Capacity__c
                        ,Model_Year__c
                        ,Number_Of_Wheels__c
                        ,Odometer_Reading__c
                        ,Resale_Value__c
                        ,Status__c
                    FROM Bus__c
                    WHERE Id = :busId
                ];   
            }      
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Bus__c saveBus(Bus__c bus) {
        try {
            UPSERT bus;
            return getBus(bus.Id);
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<PicklistItem> getStatuses() {
        List<PicklistItem> values = new List<PicklistItem>();
        Schema.DescribeFieldResult source = Bus__c.Status__c.getDescribe();
        for (Schema.PicklistEntry picklistValue : source.getPicklistValues()) {
            values.add(new PicklistItem(picklistValue.getValue(), picklistValue.getValue()));
        }
        return values;
    }

    @AuraEnabled(cacheable=true)
    public static List<PicklistItem> getCapacities() {
        List<PicklistItem> values = new List<PicklistItem>();
        Schema.DescribeFieldResult source = Bus__c.Maximum_Capacity__c.getDescribe();
        for (Schema.PicklistEntry picklistValue : source.getPicklistValues()) {
            values.add(new PicklistItem(picklistValue.getValue(), picklistValue.getValue()));
        }
        return values;
    }
}