force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <description>Contains attributes describing a bus.</description>
    <label>Bus</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Bus Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Maximum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Capacity__c</fullName>
    <inlineHelpText>The maximum capacity.</inlineHelpText>
    <label>Maximum Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Reading__c</fullName>
    <inlineHelpText>The most recently recorded odometer reading.</inlineHelpText>
    <label>Odometer Reading</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The bus status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Use</fullName>
            </value>
            <value>
                <fullName>Scheduled for Maintenance</fullName>
            </value>
            <value>
                <fullName>Undergoing Repairs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus_Garage_Association__c/Bus_Garage_Association__c.object-meta.xml
<CustomObject>
    <description>Junction object to link buses to garages that can service them.</description>
    <label>Bus Garage Association</label>
    <nameField>
        <displayFormat>BG-{000000}</displayFormat>
        <label>Bus Garage Association Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus Garage Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus_Garage_Association__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <inlineHelpText>The bus that is associated with the garage.</inlineHelpText>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Garages That Can Service Bus</relationshipLabel>
    <relationshipName>Bus_Garage_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bus_Garage_Association__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <formula>DISTANCE(GEOLOCATION(Bus__r.Last_Reported_Location__Latitude__s, Bus__r.Last_Reported_Location__Longitude__s), GEOLOCATION( Garage__r.Location__Latitude__s, Garage__r.Location__Longitude__s), &apos;mi&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The distance between the bus&apos;s current location and the garage&apos;s location in miles.</inlineHelpText>
    <label>Distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus_Garage_Association__c/fields/Garage__c.field-meta.xml
<CustomField>
    <fullName>Garage__c</fullName>
    <inlineHelpText>The garage associated with the bus.</inlineHelpText>
    <label>Garage</label>
    <referenceTo>Garage__c</referenceTo>
    <relationshipLabel>Buses Garage Can Service</relationshipLabel>
    <relationshipName>Bus_Garage_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Garage__c/Garage__c.object-meta.xml
<CustomObject>
    <description>Contains attributes describing a garage.</description>
    <label>Garage</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Garage Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Work_Order__c/Maintenance_Work_Order__c.object-meta.xml
<CustomObject>
    <description>Contains attributes describing a bus maintenance work order.</description>
    <label>Maintenance Work Order</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>Maintenace Work Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Work_Order__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The bus this work order is for.</inlineHelpText>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Maintenance Work Orders</relationshipLabel>
    <relationshipName>Maintenance_Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance_Work_Order__c/fields/Bus_Garage_Association__c.field-meta.xml
<CustomField>
    <fullName>Bus_Garage_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The bus and garage this maintenance order is for.</inlineHelpText>
    <label>Bus Garage Association</label>
    <referenceTo>Bus_Garage_Association__c</referenceTo>
    <relationshipLabel>Maintenance Work Orders</relationshipLabel>
    <relationshipName>Maintenance_Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance_Work_Order__c/fields/Garage__c.field-meta.xml
<CustomField>
    <fullName>Garage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Garage this work order is for.</inlineHelpText>
    <label>Garage</label>
    <referenceTo>Garage__c</referenceTo>
    <relationshipLabel>Maintenance Work Orders</relationshipLabel>
    <relationshipName>Maintenance_Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance_Work_Order__c/fields/Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Reading__c</fullName>
    <inlineHelpText>Bus odometer reading at time this maintenance was scehduled.</inlineHelpText>
    <label>Odometer Reading</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Maintenance_Work_Order__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <inlineHelpText>Reason for scheduling maintenance.</inlineHelpText>
    <label>Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Maintenance_Work_Order__c/fields/Scheduled_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Time__c</fullName>
    <inlineHelpText>The scheduled time of the maintenance.</inlineHelpText>
    <label>Scheduled Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BusMaintenanceScheduler.cls
global class BusMaintenanceScheduler implements Database.Batchable<sObject>, Schedulable {

    //System.schedule('Bus Maintenance Scheduler', '0, 0, 1, *, *, ?', new BusMaintenanceScheduler());

    global Database.queryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator(
            [SELECT Id
                ,Odometer_Reading__c
            FROM Bus__c
            WHERE Maximum_Capacity__c = '60']
        );
    }

    global void execute(Database.BatchableContext context, List<Bus__c> buses) {
        List<Maintenance_Work_Order__c> workOrdersToAdd = new List<Maintenance_Work_Order__c>();
        List<Bus__c> busesToUpdate = new List<Bus__c>();
        Set<Id> busIds = (new Map<Id, Bus__c>(buses).keySet());

        // Get list of bus/garage junction records with a garage that can service selected buses.
        List<Bus_Garage_Association__c> busGarages = 
            [SELECT Id
                ,Bus__r.Id
                ,Garage__r.Id
                ,Distance__c
            FROM Bus_Garage_Association__c
            WHERE Bus__r.Id IN :busIds
            ORDER BY Bus__r.Id, Distance__c];

        // Get max bus odometer reading from maintenance work orders.
        List<AggregateResult> lastBusMaintenance = 
            [SELECT Bus__r.Id BusId
                ,MAX(Odometer_Reading__c) OdometerReading
            FROM Maintenance_Work_Order__c
            WHERE Bus__r.Id IN :busIds
            GROUP BY Bus__r.Id];

        for (Bus__c bus : buses) {
            // Find the last odometer reading for the bus from the maintenace records.
            integer lastOdometerReading = 0;
            for (AggregateResult maintenace : lastBusMaintenance) {
                if (maintenace.get('BusId') == bus.Id) {
                    lastOdometerReading = integer.valueOf(maintenace.get('OdometerReading'));
                    break;
                }
            }

            if ((bus.Odometer_Reading__c - lastOdometerReading) >= 5000) {
                // It has been 5000 or more miles since last maintenance, schedule a work order.

                // Find first garage for the bus, it should be the closest to the bus location.
                string garageId = '';
                for (Bus_Garage_Association__c garageAssociation : busGarages) {
                    if (garageAssociation.Bus__r.Id == bus.Id) {
                        garageId = garageAssociation.Garage__r.Id;
                        break;
                    }
                }

                if (garageId != '') {
                    // Create maintenance work order and set bus status to Scheduled For Maintenance
                    Maintenance_Work_Order__c workOrder = new Maintenance_Work_Order__c();
                    workOrder.Bus__c = bus.Id;
                    workOrder.Garage__c = garageId;
                    workOrder.Odometer_Reading__c = bus.Odometer_Reading__c;
                    workOrder.Reason__c = 'Routine 5000 mile maintenance.';
                    workOrder.Scheduled_Time__c = DateTime.Now();
                    workOrdersToAdd.add(workOrder);
                    
                    Bus__c busToUpdate = new Bus__c();
                    busToUpdate.Id = bus.Id;
                    busToUpdate.Status__c = 'Scheduled For Maintenance';
                    busesToUpdate.add(busToUpdate);
                }
            }
        }

        if (workOrdersToAdd.size() > 0) {
            INSERT workOrdersToAdd;
        }
        if (busesToUpdate.size() > 0) {
            UPDATE busesToUpdate;
        }
    }

    global void finish(Database.BatchableContext context) {

    }

    global void execute(SchedulableContext context) {
        Database.executeBatch(new BusMaintenanceScheduler());
    }
}